// Generates supabase/seed.sql from catalog.mjs. Deterministic output.
// Usage: node scripts/seed/build.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { categories, products, img, reviewAuthors, reviewTemplates, questions, coupons, shipping, DEFAULT_METHODS, closeUps, closeUpUrl } from './catalog.mjs';

let seed = 20261004;
const rand = () => ((seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296);
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const int = (min, max) => min + Math.floor(rand() * (max - min + 1));
const uuid = () => {
  const h = Array.from({ length: 32 }, () => Math.floor(rand() * 16).toString(16));
  h[12] = '4'; h[16] = ((parseInt(h[16], 16) & 0x3) | 0x8).toString(16);
  const s = h.join('');
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-${s.slice(12, 16)}-${s.slice(16, 20)}-${s.slice(20)}`;
};
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const slugify = (s) => s.toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
/** USD → TZS, rounded to the nearest 1,000. */
const tzs = (usd) => Math.round((usd * 2600) / 1000) * 1000;
const ago = (days, hours = 0) => `now() - interval '${days} days ${hours} hours'`;

const out = ['-- Generated by scripts/seed/build.mjs. Do not edit by hand.', 'begin;',
  'truncate public.order_items, public.orders, public.reviews, public.product_questions, public.product_images,',
  '  public.product_variants, public.cart_items, public.wishlist_items, public.product_views, public.products,',
  '  public.categories, public.coupons restart identity cascade;', ''];

const catIds = {};
categories.forEach((c, i) => {
  catIds[c.slug] = uuid();
  out.push(`insert into public.categories (id, name, slug, description, image_url, sort_order) values (${q(catIds[c.slug])}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(img(c.image, 1200))}, ${i});`);
});
out.push('');

const productRows = [];
products.forEach((p, i) => {
  const id = uuid();
  const slug = slugify(p.name);
  const variants = p.variants.map((v, j) => ({ id: uuid(), ...v, sort: j }));
  const stock = variants.length ? variants.reduce((s, v) => s + v.stock, 0) : p.stock;
  const sku = `HF-${p.category.slice(0, 3).toUpperCase()}-${String(1001 + i)}`;
  productRows.push({ ...p, id, slug, variants, stock });
  if (!shipping[p.name]) throw new Error(`Missing shipping data for ${p.name}`);
  const [kg, l, w, h, methods = DEFAULT_METHODS] = shipping[p.name];
  out.push(`insert into public.products (id, category_id, name, slug, description, details, specifications, price, compare_at_price, brand, sku, stock_quantity, sales_count, is_featured, weight_kg, length_cm, width_cm, height_cm, shipping_methods, created_at, updated_at) values (` +
    [q(id), q(catIds[p.category]), q(p.name), q(slug), q(p.description),
      `array[${p.details.map(q).join(', ')}]::text[]`, `${q(JSON.stringify(p.specs))}::jsonb`,
      tzs(p.price).toFixed(2), p.compare ? tzs(p.compare).toFixed(2) : 'null', q(p.brand), q(sku), stock, p.sales,
      p.featured ? 'true' : 'false', kg, l, w, h, `array[${methods.map(q).join(', ')}]::text[]`, ago(p.days), ago(p.days)].join(', ') + ');');
  p.images.forEach((im, j) => {
    out.push(`insert into public.product_images (product_id, image_url, alt_text, sort_order) values (${q(id)}, ${q(img(im))}, ${q(`${p.name}${j ? ` – view ${j + 1}` : ''}`)}, ${j});`);
  });
  if (closeUps.has(i)) {
    out.push(`insert into public.product_images (product_id, image_url, alt_text, sort_order) values (${q(id)}, ${q(closeUpUrl(p.images[0]))}, ${q(`${p.name} – close-up detail`)}, ${p.images.length});`);
  }
  variants.forEach((v) => {
    out.push(`insert into public.product_variants (id, product_id, name, value, additional_price, stock_quantity, sort_order) values (${q(v.id)}, ${q(id)}, ${q(v.name)}, ${q(v.value)}, ${tzs(v.add ?? 0).toFixed(2)}, ${v.stock}, ${v.sort});`);
  });

  // Reviews skew positive, like real stores.
  const n = int(3, 8);
  const authors = [...reviewAuthors].sort(() => rand() - 0.5).slice(0, n);
  authors.forEach((author) => {
    const r = rand();
    const rating = r < 0.58 ? 5 : r < 0.86 ? 4 : r < 0.95 ? 3 : 2;
    const [title, content] = pick(reviewTemplates[rating]);
    out.push(`insert into public.reviews (product_id, author_name, rating, title, content, created_at) values (${q(id)}, ${q(author)}, ${rating}, ${q(title)}, ${q(content)}, ${ago(int(1, Math.max(2, p.days)), int(0, 23))});`);
  });

  // Q&A on roughly half of products
  if (i % 2 === 0) {
    [...questions].sort(() => rand() - 0.5).slice(0, int(1, 3)).forEach(([question, answer]) => {
      out.push(`insert into public.product_questions (product_id, author_name, question, answer, answered_at, created_at) values (${q(id)}, ${q(pick(reviewAuthors))}, ${q(question)}, ${q(answer)}, ${ago(int(1, 5))}, ${ago(int(6, 30))});`);
    });
  }
  out.push('');
});

coupons.forEach((c) => {
  out.push(`insert into public.coupons (code, description, type, value, min_subtotal, usage_limit, used_count, expires_at, is_active) values (${q(c.code)}, ${q(c.description)}, ${q(c.type)}, ${c.value}, ${c.min}, ${c.limit ?? 'null'}, ${int(5, 120)}, now() + interval '${c.expires} days', true);`);
});
out.push('');

// Demo guest orders over the last 60 days so the admin dashboard has history.
const firstNames = ['Amani', 'Neema', 'Baraka', 'Zawadi', 'Juma', 'Rehema', 'Imani', 'Halima', 'Saidi', 'Upendo', 'Faraja', 'Mwajuma', 'Hamisi', 'Asha', 'Daudi'];
const lastNames = ['Mushi', 'Mwakyusa', 'Kimaro', 'Massawe', 'Ngowi', 'Shirima', 'Lyimo', 'Mrema', 'Kileo', 'Temba', 'Swai', 'Msuya'];
const cities = [['Dar es Salaam', 'Dar es Salaam', 'Mikocheni'], ['Dar es Salaam', 'Dar es Salaam', 'Kinondoni'], ['Arusha', 'Arusha', 'Njiro'], ['Mwanza', 'Mwanza', 'Ilemela'], ['Dodoma', 'Dodoma', 'Area D'], ['Zanzibar', 'Mjini Magharibi', 'Mbweni'], ['Mbeya', 'Mbeya', 'Iyunga']];
for (let o = 0; o < 84; o++) {
  const id = uuid();
  const days = Math.floor(Math.pow(rand(), 1.3) * 60);
  const lines = Array.from({ length: int(1, 3) }, () => {
    const a = pick(productRows), b = pick(productRows);
    const p = a.price <= b.price ? a : b;
    const v = p.variants.length ? pick(p.variants) : null;
    return { p, v, qty: rand() < 0.8 ? 1 : 2, price: tzs(p.price + (v?.add ?? 0)) };
  });
  const subtotal = lines.reduce((s, l) => s + l.price * l.qty, 0);
  const shipping = subtotal >= 250000 ? 0 : 15000;
  const tax = Math.round(subtotal * 0.18);
  const total = subtotal + shipping + tax;
  const status = days > 10 ? (rand() < 0.92 ? 'delivered' : 'cancelled') : days > 5 ? 'shipped' : days > 2 ? 'processing' : pick(['confirmed', 'pending']);
  const fn = pick(firstNames), ln = pick(lastNames), [city, region, area] = pick(cities);
  const address = { full_name: `${fn} ${ln}`, line1: `Plot ${int(10, 990)}, ${area}`, city, region, postal_code: '', country: 'TZ', phone: `+255 7${int(10, 89)} ${int(100, 999)} ${int(100, 999)}` };
  out.push(`insert into public.orders (id, status, email, subtotal, discount, shipping, tax, total, delivery_method, shipping_address, payment_method, payment_status, created_at, updated_at) values (${q(id)}, ${q(status)}, ${q(`${fn}.${ln}@example.com`.toLowerCase())}, ${subtotal.toFixed(2)}, 0, ${shipping.toFixed(2)}, ${tax.toFixed(2)}, ${total.toFixed(2)}, ${q(pick(['standard', 'standard', 'express', 'sea']))}, ${q(JSON.stringify(address))}::jsonb, ${q(JSON.stringify({ brand: pick(['M-Pesa', 'M-Pesa', 'Tigo Pesa', 'Airtel Money', 'Visa', 'Mastercard']), last4: String(int(1000, 9999)) }))}::jsonb, ${q(status === 'cancelled' ? 'refunded' : 'paid')}, ${ago(days, int(0, 23))}, ${ago(days)});`);
  lines.forEach((l) => {
    out.push(`insert into public.order_items (order_id, product_id, product_name, product_slug, image_url, quantity, price, variant) values (${q(id)}, ${q(l.p.id)}, ${q(l.p.name)}, ${q(l.p.slug)}, ${q(img(l.p.images[0]))}, ${l.qty}, ${l.price.toFixed(2)}, ${l.v ? q(`${l.v.name}: ${l.v.value}`) : 'null'});`);
  });
}

out.push('', 'commit;', '');
const file = fileURLToPath(new URL('../../supabase/seed.sql', import.meta.url));
writeFileSync(file, out.join('\n'));
console.log(`Wrote ${file}: ${categories.length} categories, ${products.length} products.`);
