// Demo catalog. Prices below are in USD and converted to TZS by build.mjs.
// Images are from Unsplash (free to use under the Unsplash License).
export const img = (id, w = 1600) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const categories = [
  { slug: 'electronics', name: 'Electronics', image: '1618366712010-f4ae9c647dcb', description: 'Audio, wearables and desk tech, straight from Shenzhen.' },
  { slug: 'fashion', name: 'Fashion', image: '1539533018447-63fcce2678e3', description: 'Wardrobe staples from the garment makers of Guangzhou.' },
  { slug: 'footwear', name: 'Footwear', image: '1608256246200-53e635b5b65f', description: 'Runners, boots and leather classics, made to be worn in.' },
  { slug: 'beauty', name: 'Beauty', image: '1608571423902-eed4a5ad8108', description: 'Clean, effective skincare and makeup essentials.' },
  { slug: 'home', name: 'Home', image: '1578500494198-246f612d3b3d', description: 'Furniture, lighting and objects for calmer rooms.' },
  { slug: 'accessories', name: 'Accessories', image: '1524592094714-0f0654e20314', description: 'Watches, bags, jewellery and the finishing details.' },
  { slug: 'sports', name: 'Sports & Outdoors', image: '1575052814086-f385e2e2ad1b', description: 'Gear for training, trails and everything in between.' },
  { slug: 'kitchen', name: 'Kitchen & Dining', image: '1610701596061-2ecf227e85b2', description: 'Handmade ceramics and tools for slow mornings.' },
];

const sizes = (list, stock = 12) => list.map((v) => ({ name: 'Size', value: v, stock }));
const colors = (list, stock = 15) => list.map((v) => ({ name: 'Color', value: v, stock }));

// days = how many days ago it was added; sales = units sold to date
export const products = [
  // Electronics -----------------------------------------------------------
  {
    category: 'electronics', brand: 'Aurel', name: 'Aurel Studio Wireless Headphones', price: 279, compare: 349, stock: 64, sales: 1840, days: 40, featured: true,
    images: ['1618366712010-f4ae9c647dcb', '1546435770-a3e426bf472b', '1505740420928-5e560c06d30e'],
    description: 'Studio-grade sound without the studio. Adaptive noise cancelling reads your surroundings 200 times a second, while 40mm beryllium-coated drivers deliver detail you can feel. Memory-foam cushions wrapped in protein leather keep long listening sessions comfortable.',
    details: ['Adaptive active noise cancelling with transparency mode', 'Up to 38 hours of playback, 10 minutes = 5 hours', 'Multipoint Bluetooth 5.3 with LDAC', 'Folds flat into a recycled felt case'],
    specs: { Drivers: '40mm beryllium-coated', 'Battery life': '38 hours (ANC on)', Charging: 'USB-C, fast charge', Weight: '254 g', Connectivity: 'Bluetooth 5.3, 3.5mm' },
    variants: colors(['Midnight', 'Sand', 'Slate'], 20),
  },
  {
    category: 'electronics', brand: 'Aurel', name: 'Aurel Halo On-Ear Headphones', price: 149, stock: 38, sales: 620, days: 120,
    images: ['1484704849700-f032a568e944', '1583394838336-acd977736f90'],
    description: 'A lighter take on the Aurel sound. Brushed aluminium cups, walnut-finish sliders and a tuned bass port give Halo a warm, natural signature that suits everything from vinyl rips to podcasts.',
    details: ['Wired and wireless listening', '30-hour battery', 'Fold-flat hinge', 'Built-in mic with wind reduction'],
    specs: { Drivers: '32mm dynamic', 'Battery life': '30 hours', Weight: '186 g', Connectivity: 'Bluetooth 5.2, 3.5mm' },
    variants: [],
  },
  {
    category: 'electronics', brand: 'Kova', name: 'Kova Pods Pro Earbuds', price: 189, compare: 229, stock: 120, sales: 2410, days: 25, featured: true,
    images: ['1590658268037-6bf12165a8df', '1606220588913-b3aacb4d2f46', '1588423771073-b8903fbb85b5'],
    description: 'Big sound, tiny footprint. Kova Pods Pro pair dual drivers with hybrid noise cancelling and a pocket-sized wireless charging case, so the music never has to stop.',
    details: ['Hybrid ANC with three microphones per bud', 'IPX5 sweat and water resistance', 'Wireless charging case', 'Spatial audio with head tracking'],
    specs: { 'Battery life': '8 h (buds) + 28 h (case)', 'Water resistance': 'IPX5', Charging: 'USB-C, Qi wireless', Weight: '5.1 g per bud' },
    variants: colors(['Graphite', 'Cloud'], 40),
  },
  {
    category: 'electronics', brand: 'Nordlys', name: 'Nordlys Pulse Smartwatch', price: 329, stock: 46, sales: 980, days: 12, featured: true,
    images: ['1617043786394-f977fa12eddf', '1546868871-7041f2a55e12'],
    description: 'Your health, at a glance. Pulse tracks heart rate, blood oxygen, sleep stages and 120 workout types on a bright always-on AMOLED display, then keeps going for a full week on a single charge.',
    details: ['1.9" always-on AMOLED display', 'Dual-band GPS', '7-day battery life', 'Swim-proof to 50 m'],
    specs: { Display: '1.9" AMOLED, 2000 nits', Sensors: 'HR, SpO2, skin temperature', 'Water resistance': '5 ATM', Battery: 'Up to 7 days' },
    variants: [{ name: 'Case', value: '41mm', stock: 22 }, { name: 'Case', value: '45mm', stock: 24, add: 30 }],
  },
  {
    category: 'electronics', brand: 'Nordlys', name: 'Nordlys Arc Ceramic Watch', price: 249, compare: 299, stock: 18, sales: 410, days: 210,
    images: ['1523275335684-37898b6baf30'],
    description: 'A smartwatch dressed as a classic. A polished white ceramic case and fluoroelastomer strap hide everyday smarts: notifications, contactless payments and quiet haptic alarms.',
    details: ['Scratch-resistant ceramic case', 'Contactless payments', '5-day battery', 'Interchangeable 20mm straps'],
    specs: { Case: '40mm ceramic', 'Water resistance': '3 ATM', Battery: 'Up to 5 days' },
    variants: [],
  },
  {
    category: 'electronics', brand: 'Kova', name: 'Kova Reference Bookshelf Speakers', price: 449, stock: 14, sales: 175, days: 90,
    images: ['1545454675-3531b543be5d'],
    description: 'Room-filling sound from a pair of compact cabinets. A silk-dome tweeter and woven-fibre woofer are tuned for accuracy, with a built-in amplifier, phono stage and HDMI ARC for your TV.',
    details: ['Powered pair with built-in 120 W amplifier', 'HDMI ARC, optical, phono and Bluetooth inputs', 'Real walnut veneer', 'Remote included'],
    specs: { Power: '2 × 60 W', 'Frequency response': '45 Hz – 25 kHz', Dimensions: '29 × 18 × 23 cm (each)' },
    variants: [],
  },
  {
    category: 'electronics', brand: 'Vale', name: 'Vale 14 Ultrabook', price: 1299, compare: 1449, stock: 22, sales: 312, days: 8,
    images: ['1496181133206-80ce9b88a853', '1593642632559-0c6d3fc62b89'],
    description: 'All-day power in 1.2 kilograms. The Vale 14 pairs a 2.8K OLED display with a silent, fanless design and an aluminium unibody you\'ll actually want to carry everywhere.',
    details: ['14" 2.8K OLED, 120 Hz', 'Fanless, silent design', 'Up to 20 hours of battery', 'Two Thunderbolt 4 ports'],
    specs: { Display: '14" 2880 × 1800 OLED', Storage: '1 TB SSD', Weight: '1.2 kg', Ports: '2 × Thunderbolt 4, 3.5mm' },
    variants: [{ name: 'Memory', value: '16 GB', stock: 12 }, { name: 'Memory', value: '32 GB', stock: 10, add: 200 }],
  },
  {
    category: 'electronics', brand: 'Kova', name: 'Kova K2 Mechanical Keyboard', price: 129, stock: 75, sales: 860, days: 4,
    images: ['1595225476474-87563907a212', '1587829741301-dc798b83add3'],
    description: 'A keyboard that makes you want to write. Hot-swappable switches, PBT keycaps in a retro colourway and a gasket-mounted plate give every keystroke a soft, satisfying thock.',
    details: ['Gasket-mounted 75% layout', 'Hot-swappable switches', 'Double-shot PBT keycaps', 'Wireless and wired modes'],
    specs: { Layout: '75% (84 keys)', Switches: 'Linear, pre-lubed', Connectivity: 'Bluetooth, 2.4 GHz, USB-C' },
    variants: [{ name: 'Switch', value: 'Linear', stock: 40 }, { name: 'Switch', value: 'Tactile', stock: 35 }],
  },

  // Fashion ----------------------------------------------------------------
  {
    category: 'fashion', brand: 'Fieldwork', name: 'Heavyweight Organic Cotton Tee', price: 42, stock: 210, sales: 3120, days: 60, featured: true,
    images: ['1521572163474-6864f9cf17ab'],
    description: 'The tee everything else is built around. Knitted from 240 gsm organic cotton with a structured neckline that keeps its shape wash after wash, cut with a slightly boxy fit.',
    details: ['240 gsm organic cotton jersey', 'Boxy, slightly cropped fit', 'Ribbed crew neck', 'Garment-washed for softness'],
    specs: { Material: '100% organic cotton', Fit: 'Relaxed', Care: 'Machine wash cold' },
    variants: sizes(['XS', 'S', 'M', 'L', 'XL'], 40),
  },
  {
    category: 'fashion', brand: 'Maison Ode', name: 'Leather Biker Jacket', price: 420, compare: 560, stock: 16, sales: 290, days: 30, featured: true,
    images: ['1551028719-00167b16eac5'],
    description: 'A modern heirloom. Cut from vegetable-tanned lambskin that softens and patinas with wear, with an asymmetric zip, quilted shoulders and a fully lined body.',
    details: ['Vegetable-tanned lambskin', 'Asymmetric YKK zip', 'Quilted cupro lining', 'Gets better with age'],
    specs: { Material: 'Lambskin leather', Lining: '100% cupro', Fit: 'True to size' },
    variants: sizes(['XS', 'S', 'M', 'L'], 4),
  },
  {
    category: 'fashion', brand: 'Linea', name: 'Camel Wool Wrap Coat', price: 345, stock: 28, sales: 205, days: 3, featured: true,
    images: ['1539533018447-63fcce2678e3'],
    description: 'An investment coat in an Italian wool-cashmere blend. Dropped shoulders, deep patch pockets and a self-tie belt make it as easy over a hoodie as it is over tailoring.',
    details: ['Italian wool-cashmere blend', 'Removable self-tie belt', 'Fully lined', 'Falls just below the knee'],
    specs: { Material: '90% wool, 10% cashmere', Fit: 'Relaxed, oversized', Care: 'Dry clean only' },
    variants: sizes(['XS', 'S', 'M', 'L'], 7),
  },
  {
    category: 'fashion', brand: 'Fieldwork', name: 'Selvedge Straight-Leg Jeans', price: 135, stock: 84, sales: 1120, days: 75,
    images: ['1604176354204-9268737828e4', '1638247025967-b4e38f787b76'],
    description: 'Woven on vintage shuttle looms in Okayama, Japan. 13.5 oz rigid selvedge denim that moulds to you over time, in a straight leg that works with everything.',
    details: ['13.5 oz Japanese selvedge denim', 'Mid rise, straight leg', 'Copper rivets and chain-stitched hems', 'Unwashed for custom fading'],
    specs: { Material: '100% cotton', Rise: 'Mid', Inseam: '32"' },
    variants: sizes(['28', '30', '32', '34', '36'], 16),
  },
  {
    category: 'fashion', brand: 'Maison Ode', name: 'Silk-Blend Midi Dress', price: 228, compare: 285, stock: 30, sales: 340, days: 18,
    images: ['1572804013309-59a88b7e92f1', '1595777457583-95e059d581b8'],
    description: 'Fluid, flattering, unforgettable. A silk-blend dress with a softly gathered waist, flutter sleeves and a hem that moves beautifully, from summer weddings to dinner on the coast.',
    details: ['Silk-viscose blend', 'Flutter sleeves, V-neck', 'Concealed side zip', 'Midi length'],
    specs: { Material: '52% silk, 48% viscose', Length: '118 cm (size S)', Care: 'Hand wash cold' },
    variants: sizes(['XS', 'S', 'M', 'L'], 8),
  },
  {
    category: 'fashion', brand: 'Linea', name: 'Satin Bomber Jacket', price: 168, compare: 210, stock: 26, sales: 270, days: 150,
    images: ['1591047139829-d91aecb6caea'],
    description: 'A lightweight bomber with a soft sheen. Ribbed cuffs and hem, a two-way zip and a quilted lining make it the perfect transitional layer.',
    details: ['Recycled satin shell', 'Light quilted lining', 'Two-way metal zip', 'Interior pocket'],
    specs: { Material: '100% recycled polyester', Fit: 'Regular' },
    variants: sizes(['S', 'M', 'L', 'XL'], 6),
  },
  {
    category: 'fashion', brand: 'Fieldwork', name: 'Loopback Crewneck Sweatshirt', price: 88, stock: 140, sales: 1530, days: 100,
    images: ['1620799140408-edc6dcb6d633'],
    description: 'Heavyweight loopback cotton that gets softer every wear. Cut with a relaxed body, raglan sleeves and a reinforced neck that won\'t stretch out.',
    details: ['400 gsm loopback cotton', 'Raglan sleeves', 'Pre-shrunk', 'Made in Portugal'],
    specs: { Material: '100% organic cotton', Fit: 'Relaxed' },
    variants: sizes(['S', 'M', 'L', 'XL'], 35),
  },
  {
    category: 'fashion', brand: 'Linea', name: 'Washed Chambray Shirt', price: 98, stock: 64, sales: 480, days: 45,
    images: ['1596755094514-f87e34085b2c', '1602810318383-e386cc2a3ccf'],
    description: 'An everyday shirt in a soft, washed chambray with a subtle micro print. Tuck it, layer it, or wear it open over a tee.',
    details: ['Washed cotton chambray', 'Mother-of-pearl buttons', 'Curved hem', 'Single chest pocket'],
    specs: { Material: '100% cotton', Fit: 'Regular' },
    variants: sizes(['S', 'M', 'L', 'XL'], 16),
  },

  // Footwear -------------------------------------------------------------
  {
    category: 'footwear', brand: 'Strider', name: 'Strider Aero Running Shoe', price: 160, compare: 190, stock: 92, sales: 2210, days: 20, featured: true,
    images: ['1491553895911-0055eca6402d'],
    description: 'Engineered for your fastest miles. A supercritical foam midsole returns energy with every stride, and a breathable engineered-mesh upper locks your foot in without pressure points.',
    details: ['Supercritical PEBA foam midsole', '8 mm drop', 'Engineered mesh upper', 'Weighs just 218 g (US 9)'],
    specs: { Drop: '8 mm', Weight: '218 g', Use: 'Road running, racing' },
    variants: sizes(['7', '8', '9', '10', '11', '12'], 15),
  },
  {
    category: 'footwear', brand: 'Arlo & Pine', name: 'Heritage Lace-Up Boot', price: 295, stock: 40, sales: 640, days: 70, featured: true,
    images: ['1608256246200-53e635b5b65f', '1520639888713-7851133b1ed0'],
    description: 'A boot built to be resoled, not replaced. Full-grain leather, a Goodyear-welted construction and a Vibram lug sole that grips in any weather.',
    details: ['Full-grain oiled leather', 'Goodyear-welted, fully resoleable', 'Vibram lug sole', 'Cork footbed moulds to your foot'],
    specs: { Upper: 'Full-grain leather', Sole: 'Vibram rubber', Construction: 'Goodyear welt' },
    variants: sizes(['8', '9', '10', '11', '12'], 8),
  },
  {
    category: 'footwear', brand: 'Arlo & Pine', name: 'Double Monk Strap Shoe', price: 245, compare: 310, stock: 24, sales: 190, days: 130,
    images: ['1533867617858-e7b97e060509', '1614252235316-8c857d38b5f4'],
    description: 'Hand-burnished calfskin and a sleek almond toe. A smarter alternative to the lace-up that pairs equally well with a suit or cuffed denim.',
    details: ['Hand-burnished calfskin', 'Leather sole with rubber heel', 'Brushed brass buckles', 'Made in Spain'],
    specs: { Upper: 'Calfskin leather', Sole: 'Leather and rubber' },
    variants: sizes(['8', '9', '10', '11'], 6),
  },
  {
    category: 'footwear', brand: 'Strider', name: 'Court Classic Canvas Sneaker', price: 75, stock: 150, sales: 2840, days: 200,
    images: ['1525966222134-fcfa99b8ae77'],
    description: 'The low-top you\'ll reach for every day. Heavy cotton canvas, a vulcanised gum-rubber sole and a cushioned insole that makes the classic shape comfortable all day.',
    details: ['12 oz cotton canvas', 'Vulcanised rubber sole', 'Removable cushioned insole'],
    specs: { Upper: 'Cotton canvas', Sole: 'Vulcanised rubber' },
    variants: sizes(['6', '7', '8', '9', '10', '11'], 25),
  },
  {
    category: 'footwear', brand: 'Strider', name: 'Strider Terra Trail Sneaker', price: 140, stock: 0, sales: 760, days: 55,
    images: ['1560769629-975ec94e6a86'],
    description: 'A chunky trail sneaker that is as comfortable on the commute as it is on gravel. A rock plate protects underfoot and the sticky outsole grips wet ground.',
    details: ['Protective rock plate', 'Sticky rubber outsole', 'Water-resistant suede overlays'],
    specs: { Drop: '6 mm', Use: 'Trail, everyday' },
    variants: [],
  },
  {
    category: 'footwear', brand: 'Arlo & Pine', name: 'Suede Derby Shoe', price: 195, stock: 32, sales: 230, days: 6,
    images: ['1560343090-f0409e92791a'],
    description: 'A soft, unstructured derby in seasonal sage suede. Blake-stitched for flexibility from the first wear, on a lightweight crepe sole.',
    details: ['Italian suede', 'Blake-stitched construction', 'Natural crepe sole'],
    specs: { Upper: 'Suede', Sole: 'Crepe rubber' },
    variants: sizes(['7', '8', '9', '10', '11'], 7),
  },

  // Beauty ---------------------------------------------------------------
  {
    category: 'beauty', brand: 'Solène', name: 'Radiance Vitamin C Serum', price: 58, compare: 72, stock: 180, sales: 4210, days: 35, featured: true,
    images: ['1608571423902-eed4a5ad8108', '1620916297397-a4a5402a3c6c'],
    description: 'A brightening serum with 15% stabilised vitamin C, ferulic acid and vitamin E. Visibly evens tone and boosts glow in four weeks, without stinging sensitive skin.',
    details: ['15% stabilised vitamin C', 'Fragrance-free, vegan', 'Suitable for sensitive skin', 'Amber glass dropper bottle'],
    specs: { Size: '30 ml', 'Skin type': 'All skin types', 'Key ingredients': 'Vitamin C, ferulic acid, vitamin E' },
    variants: [{ name: 'Size', value: '30 ml', stock: 100 }, { name: 'Size', value: '50 ml', stock: 80, add: 24 }],
  },
  {
    category: 'beauty', brand: 'Botanica Lab', name: 'Restorative Botanical Face Oil', price: 64, stock: 95, sales: 1380, days: 85,
    images: ['1617897903246-719242758050', '1612817288484-6f916006741a'],
    description: 'Cold-pressed rosehip, squalane and bakuchiol in a silky dry oil that sinks in fast. Wake up to skin that looks plumper, calmer and deeply nourished.',
    details: ['Cold-pressed rosehip and squalane', 'Bakuchiol: gentle retinol alternative', 'Non-comedogenic'],
    specs: { Size: '30 ml', 'Skin type': 'Dry, normal, combination' },
    variants: [],
  },
  {
    category: 'beauty', brand: 'Solène', name: 'Daily Hydrating Body Lotion', price: 34, stock: 220, sales: 2650, days: 140,
    images: ['1631729371254-42c2892f0e6e'],
    description: 'A fast-absorbing body lotion with ceramides and niacinamide that hydrates for 48 hours. A clean scent of fig leaf and cedar that never overpowers.',
    details: ['48-hour hydration', 'Ceramides and niacinamide', 'Dermatologist tested'],
    specs: { Size: '400 ml', Scent: 'Fig leaf and cedar' },
    variants: [],
  },
  {
    category: 'beauty', brand: 'Solène', name: 'Complete Face Brush Set', price: 72, compare: 96, stock: 60, sales: 870, days: 10,
    images: ['1596462502278-27bfdc403348'],
    description: 'Seven ultra-soft synthetic brushes for foundation, powder, blush and eyes, with rose-gold ferrules and weighted handles.',
    details: ['7 synthetic, cruelty-free brushes', 'Weighted handles', 'Vegan leather travel roll'],
    specs: { Pieces: '7', Bristles: 'Synthetic taklon' },
    variants: [],
  },
  {
    category: 'beauty', brand: 'Botanica Lab', name: 'Velvet Lip & Cheek Collection', price: 48, stock: 75, sales: 640, days: 28,
    images: ['1571875257727-256c39da42af'],
    description: 'Five buildable shades of creamy colour for lips and cheeks, in a slim palette that slips into any bag. Infused with shea and rosehip for comfortable wear.',
    details: ['5 multi-use shades', 'Shea and rosehip oil', 'Mirror included'],
    specs: { Shades: '5', Finish: 'Velvet satin' },
    variants: [],
  },

  // Home -----------------------------------------------------------------
  {
    category: 'home', brand: 'Oaken', name: 'Velvet Three-Seat Sofa', price: 1690, compare: 1990, stock: 9, sales: 84, days: 50, featured: true,
    images: ['1555041469-a586c61ea9bc'],
    description: 'Mid-century lines with modern comfort. Deep feather-wrapped cushions sit on a kiln-dried hardwood frame, upholstered in a stain-resistant performance velvet.',
    details: ['Kiln-dried solid hardwood frame', 'Feather-wrapped foam cushions', 'Stain-resistant performance velvet', 'Free white-glove delivery'],
    specs: { Dimensions: 'W 214 × D 92 × H 82 cm', 'Seat height': '45 cm', Material: 'Performance velvet, oak legs' },
    variants: colors(['Emerald', 'Ochre', 'Ink'], 3),
  },
  {
    category: 'home', brand: 'Hearth & Co', name: 'Sculpted Stoneware Vase', price: 86, stock: 44, sales: 520, days: 14,
    images: ['1612196808214-b8e1d6145a8c'],
    description: 'A generous, rounded vase thrown by hand and finished in a matte bone glaze. Beautiful on its own, or with a single dramatic stem.',
    details: ['Hand-thrown stoneware', 'Matte bone glaze', 'Watertight interior', 'Each piece is unique'],
    specs: { Height: '32 cm', Material: 'Stoneware' },
    variants: [],
  },
  {
    category: 'home', brand: 'Oaken', name: 'Turned Ash Bud Vases, Set of 2', price: 54, stock: 52, sales: 380, days: 95,
    images: ['1584589167171-541ce45f1eea'],
    description: 'A pair of turned ash vases with glass inserts. Their soft, organic shapes bring warmth to shelves, sills and side tables.',
    details: ['Solid ash, oil finish', 'Removable glass inserts', 'Set of two heights'],
    specs: { Heights: '14 cm and 18 cm', Material: 'Ash wood, glass' },
    variants: [],
  },
  {
    category: 'home', brand: 'Hearth & Co', name: 'Amber Glass Scented Candle', price: 38, stock: 160, sales: 2980, days: 22,
    images: ['1572726729207-a78d6feb18d7', '1603006905003-be475563bc59'],
    description: 'Coconut-soy wax poured into reusable amber glass, with a cotton wick that burns clean for 60 hours. Notes of fig, cedarwood and a little smoke.',
    details: ['Coconut-soy wax blend', '60-hour burn time', 'Phthalate-free fragrance', 'Reusable glass vessel'],
    specs: { Weight: '300 g', 'Burn time': '60 hours' },
    variants: [{ name: 'Scent', value: 'Fig & Cedar', stock: 60 }, { name: 'Scent', value: 'Amber & Smoke', stock: 50 }, { name: 'Scent', value: 'Sea Salt & Sage', stock: 50 }],
  },
  {
    category: 'home', brand: 'Oaken', name: 'Lounge Armchair', price: 640, stock: 11, sales: 96, days: 7,
    images: ['1586023492125-27b2c045efd7'],
    description: 'A compact armchair with a generous, enveloping seat. Solid oak legs and a sculpted back make it a statement in any corner.',
    details: ['Solid oak legs', 'High-resilience foam seat', 'Woven bouclé or textured weave'],
    specs: { Dimensions: 'W 76 × D 80 × H 78 cm', Material: 'Oak, textured weave' },
    variants: colors(['Mustard', 'Oat'], 5),
  },
  {
    category: 'home', brand: 'Hearth & Co', name: 'Task Floor Lamp', price: 189, compare: 239, stock: 27, sales: 310, days: 160,
    images: ['1507473885765-e6ed057f782c'],
    description: 'An industrial-inspired floor lamp with an adjustable powder-coated shade, perfect for reading corners and desks.',
    details: ['Adjustable steel shade', 'Weighted base', 'E27 bulb included', 'In-line dimmer'],
    specs: { Height: '152 cm', Material: 'Powder-coated steel' },
    variants: [],
  },
  {
    category: 'home', brand: 'Hearth & Co', name: 'Brass Dome Pendant Light', price: 219, stock: 19, sales: 140, days: 65,
    images: ['1540932239986-30128078f3c5', '1513506003901-1e6a229e2d15'],
    description: 'A spun-metal dome pendant that casts a warm, focused pool of light over dining tables and kitchen islands.',
    details: ['Spun aluminium shade', 'Adjustable cord drop', 'Dimmable'],
    specs: { Diameter: '38 cm', Cord: '200 cm, adjustable' },
    variants: colors(['Brass', 'Teal'], 9),
  },
  {
    category: 'home', brand: 'Oaken', name: 'Molded Dining Chair, Set of 2', price: 260, stock: 34, sales: 225, days: 110,
    images: ['1592078615290-033ee584e267'],
    description: 'An iconic molded silhouette with a padded seat and solid beech legs. Comfortable for long dinners and easy to wipe clean.',
    details: ['Set of two chairs', 'Padded seat cushion', 'Solid beech legs'],
    specs: { 'Seat height': '46 cm', Material: 'Polypropylene, beech' },
    variants: colors(['Black', 'White'], 15),
  },
  {
    category: 'home', brand: 'Hearth & Co', name: 'Cloud Down Pillow', price: 89, stock: 96, sales: 1150, days: 190,
    images: ['1584100936595-c0654b55a2e2'],
    description: 'Responsibly sourced down in a 400-thread-count cotton sateen shell. Plump and supportive, with a medium loft that suits most sleepers.',
    details: ['RDS-certified down', '400 TC cotton sateen shell', 'Medium loft'],
    specs: { Size: 'Standard 50 × 75 cm', Fill: '90% down, 10% feather' },
    variants: [{ name: 'Size', value: 'Standard', stock: 50 }, { name: 'Size', value: 'King', stock: 46, add: 20 }],
  },

  // Accessories ----------------------------------------------------------
  {
    category: 'accessories', brand: 'Vire', name: 'Vire Field Automatic Watch', price: 495, compare: 580, stock: 21, sales: 260, days: 42, featured: true,
    images: ['1509941943102-10c232535736', '1547996160-81dfa63595aa'],
    description: 'A rugged automatic for everyday adventures. A Swiss-made movement, sapphire crystal and 100 m water resistance, on a vegetable-tanned leather strap.',
    details: ['Swiss automatic movement, 38-hour reserve', 'Sapphire crystal', '100 m water resistance', 'Quick-release leather strap'],
    specs: { Case: '39mm stainless steel', Movement: 'Swiss automatic', 'Water resistance': '10 ATM' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Vire', name: 'Vire Minimal 38 Watch', price: 225, stock: 48, sales: 730, days: 160,
    images: ['1524592094714-0f0654e20314', '1585123334904-845d60e97b29'],
    description: 'Clean dial, slim case, nothing extra. A Japanese quartz movement inside a 6.5mm case that slips under any cuff.',
    details: ['6.5mm slim case', 'Japanese quartz', 'Sapphire-coated crystal'],
    specs: { Case: '38mm', 'Water resistance': '5 ATM' },
    variants: [{ name: 'Strap', value: 'Sand leather', stock: 24 }, { name: 'Strap', value: 'Blue rubber', stock: 24 }],
  },
  {
    category: 'accessories', brand: 'Vire', name: 'Round Wire Sunglasses', price: 145, stock: 66, sales: 980, days: 33,
    images: ['1511499767150-a48a237f0083'],
    description: 'Featherweight titanium frames with polarised, scratch-resistant lenses. A timeless round shape that suits almost every face.',
    details: ['Titanium frame, 14 g', 'Polarised CR-39 lenses', '100% UVA/UVB protection', 'Hard case and cloth included'],
    specs: { Frame: 'Titanium', Lens: 'Polarised, category 3' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Maison Ode', name: 'Top-Handle Leather Bag', price: 385, compare: 450, stock: 15, sales: 220, days: 16, featured: true,
    images: ['1584917865442-de89df76afd3'],
    description: 'A structured top-handle bag in glossy calfskin with a polished turn-lock. Detachable strap for cross-body wear.',
    details: ['Glossy calfskin', 'Detachable cross-body strap', 'Suede-lined interior', 'Fits a phone, wallet and keys'],
    specs: { Dimensions: '24 × 19 × 10 cm', Material: 'Calfskin leather' },
    variants: colors(['Scarlet', 'Black'], 7),
  },
  {
    category: 'accessories', brand: 'Maison Ode', name: 'Woven Basket Bag', price: 165, stock: 38, sales: 410, days: 5,
    images: ['1590874103328-eac38a683ce7'],
    description: 'Hand-woven rattan meets smooth leather in this summer-to-city top-handle bag.',
    details: ['Hand-woven rattan', 'Leather handle and trim', 'Cotton drawstring lining'],
    specs: { Dimensions: '28 × 22 × 14 cm' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Fieldwork', name: 'Commuter Backpack 22L', price: 128, stock: 70, sales: 1320, days: 80,
    images: ['1553062407-98eeb64c6a62'],
    description: 'A clean, weatherproof backpack with a padded 16" laptop sleeve, a quick-access top pocket and a luggage pass-through.',
    details: ['Water-resistant recycled nylon', 'Padded 16" laptop sleeve', 'Luggage pass-through', 'Lifetime warranty'],
    specs: { Volume: '22 L', Weight: '0.9 kg' },
    variants: colors(['Navy', 'Black'], 35),
  },
  {
    category: 'accessories', brand: 'Fieldwork', name: 'Leather Rucksack', price: 265, compare: 320, stock: 12, sales: 160, days: 140,
    images: ['1622560480605-d83c853bc5c3'],
    description: 'A full-grain leather rucksack that ages beautifully. Roomy main compartment, padded laptop sleeve and solid brass hardware.',
    details: ['Full-grain leather', 'Padded 15" laptop sleeve', 'Solid brass hardware'],
    specs: { Volume: '18 L', Material: 'Full-grain leather' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Vire', name: 'Freshwater Pearl Pendant', price: 120, stock: 54, sales: 690, days: 26,
    images: ['1611085583191-a3b181a88401'],
    description: 'A single freshwater pearl on a fine 14k gold-filled chain. Delicate enough for every day, special enough for occasions.',
    details: ['Freshwater pearl, 7–8 mm', '14k gold-filled chain', 'Adjustable 40–45 cm'],
    specs: { Metal: '14k gold-filled', Length: '40–45 cm' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Vire', name: 'Heirloom Pearl Strand', price: 340, stock: 10, sales: 85, days: 180,
    images: ['1515562141207-7a88fb7ce338'],
    description: 'A hand-knotted strand of lustrous freshwater pearls with a sterling silver clasp, presented in a keepsake box.',
    details: ['Hand-knotted on silk', 'Sterling silver clasp', 'Gift box included'],
    specs: { Length: '45 cm', Pearls: '7–7.5 mm freshwater' },
    variants: [],
  },
  {
    category: 'accessories', brand: 'Vire', name: 'Leather Bifold Wallet', price: 79, stock: 120, sales: 1480, days: 120,
    images: ['1627123424574-724758594e93'],
    description: 'A slim bifold in vegetable-tanned leather with six card slots and a full-length note pocket.',
    details: ['Vegetable-tanned leather', '6 card slots', 'RFID-blocking lining'],
    specs: { Dimensions: '11 × 9 cm' },
    variants: [],
  },

  // Sports ---------------------------------------------------------------
  {
    category: 'sports', brand: 'Strider', name: 'Align Pro Yoga Mat', price: 98, compare: 118, stock: 88, sales: 1720, days: 38, featured: true,
    images: ['1601925260368-ae2f83cf8b7f', '1518611012118-696072aa579a'],
    description: 'Grippy when you sweat, cushioned where it counts. A 5 mm natural rubber base with a polyurethane top layer that stays put through every flow.',
    details: ['Natural tree rubber base', 'Moisture-wicking PU top layer', 'Alignment guides', 'Carry strap included'],
    specs: { Dimensions: '183 × 68 cm', Thickness: '5 mm', Weight: '2.5 kg' },
    variants: colors(['Moss', 'Plum', 'Charcoal'], 30),
  },
  {
    category: 'sports', brand: 'Summit Supply', name: 'Insulated Steel Bottle 750ml', price: 36, stock: 300, sales: 3890, days: 90,
    images: ['1602143407151-7111542de6e8'],
    description: 'Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12. Powder-coated for grip and built to last a lifetime.',
    details: ['Cold 24 h, hot 12 h', '18/8 stainless steel', 'Leak-proof lid', 'BPA-free'],
    specs: { Capacity: '750 ml', Weight: '380 g' },
    variants: colors(['Sage', 'Sand', 'Black'], 100),
  },
  {
    category: 'sports', brand: 'Strider', name: 'Adjustable Dumbbell 24kg', price: 349, compare: 399, stock: 20, sales: 410, days: 48,
    images: ['1583454110551-21f2fa2afe61', '1517836357463-d25dfeac3438'],
    description: 'Fifteen dumbbells in one. Turn the dial to select 2.5–24 kg in seconds, with a compact cradle that saves space at home.',
    details: ['2.5–24 kg in 2.5 kg increments', 'Quick-select dial', 'Sold individually'],
    specs: { 'Weight range': '2.5–24 kg', Material: 'Steel, TPU coating' },
    variants: [],
  },
  {
    category: 'sports', brand: 'Summit Supply', name: 'Ridgeline 2-Person Tent', price: 399, stock: 13, sales: 145, days: 2,
    images: ['1504280390367-361c6d9f38f4'],
    description: 'A freestanding, three-season tent that pitches in under five minutes. Two doors, two vestibules and a full-mesh inner for star-gazing nights.',
    details: ['Freestanding, 3-season', 'Two doors and vestibules', 'Packed weight 1.6 kg', 'Footprint included'],
    specs: { 'Packed weight': '1.6 kg', 'Floor area': '2.8 m²', Capacity: '2 people' },
    variants: [],
  },
  {
    category: 'sports', brand: 'Summit Supply', name: 'Urban Steel Road Bike', price: 1150, compare: 1290, stock: 7, sales: 52, days: 58,
    images: ['1532298229144-0ec0c57515c7'],
    description: 'A timeless steel road bike with modern components. Reynolds 725 tubing, hydraulic disc brakes and clearance for 35 mm tyres.',
    details: ['Reynolds 725 steel frame', 'Hydraulic disc brakes', '2 × 11 speed drivetrain', 'Clearance for 35 mm tyres'],
    specs: { Frame: 'Reynolds 725 steel', Weight: '9.8 kg (size M)' },
    variants: sizes(['S', 'M', 'L'], 2),
  },

  // Kitchen --------------------------------------------------------------
  {
    category: 'kitchen', brand: 'Kiln Studio', name: 'Speckled Stoneware Cups, Set of 4', price: 56, stock: 80, sales: 1260, days: 11, featured: true,
    images: ['1610701596007-11502861dcfa'],
    description: 'Handleless cups thrown in small batches, with a speckled oatmeal glaze and raw clay foot. Made for espresso, tea and everything in between.',
    details: ['Set of 4', 'Dishwasher and microwave safe', 'Hand-glazed, slight variations'],
    specs: { Capacity: '220 ml', Material: 'Stoneware' },
    variants: [],
  },
  {
    category: 'kitchen', brand: 'Kiln Studio', name: 'Stoneware Dinner Set, 12 Pieces', price: 189, compare: 230, stock: 25, sales: 340, days: 66,
    images: ['1610701596061-2ecf227e85b2'],
    description: 'Dinner plates, side plates and bowls for four, in a soft reactive glaze that makes every meal feel considered.',
    details: ['4 dinner plates, 4 side plates, 4 bowls', 'Reactive glaze', 'Dishwasher safe'],
    specs: { Pieces: '12', Material: 'Stoneware' },
    variants: colors(['Oat', 'Celadon'], 12),
  },
  {
    category: 'kitchen', brand: 'Kiln Studio', name: 'Pour-Over Coffee Set', price: 74, stock: 46, sales: 520, days: 30,
    images: ['1517705008128-361805f42e86'],
    description: 'A ceramic dripper, glass carafe and two cups for the slow, ritual cup. Brews a clean, sweet coffee that highlights every origin.',
    details: ['Ceramic dripper', '600 ml borosilicate carafe', 'Two stoneware cups', '40 paper filters'],
    specs: { Capacity: '600 ml' },
    variants: [],
  },
];

export const reviewAuthors = ['Neema M.', 'Baraka K.', 'Zawadi L.', 'Juma S.', 'Rehema A.', 'Imani N.', 'Halima O.', 'Daudi T.', 'Upendo R.',
  'Faraja M.', 'Asha H.', 'Hamisi J.', 'Amani P.', 'Mwajuma K.', 'Saidi B.', 'Grace W.', 'Joseph M.', 'Esther N.', 'Emmanuel K.', 'Agnes L.'];

export const reviewTemplates = {
  5: [
    ['Worth every shilling', 'Arrived in Dar in 11 days by air cargo, well packed. The quality is better than what I found in Kariakoo for double the price.'],
    ['Exceeded my expectations', 'I was worried about ordering from China but tracking was clear the whole way and it arrived exactly as pictured.'],
    ['Beautifully made', 'Lovely details and it feels built to last. Already ordered a second one as a gift for my sister in Arusha.'],
    ['Exactly as pictured', 'Paid with M-Pesa, delivered to my door in Mikocheni. No customs stress at all. Highly recommend.'],
  ],
  4: [
    ['Really good, slow by sea', 'Great quality and a fair price. Sea freight took about five weeks, so choose air if you need it sooner.'],
    ['Solid choice', 'Does exactly what it says. Not perfect, but excellent for the price and I have no regrets.'],
    ['Very happy', 'Comfortable and well made. Sizing runs slightly small (Asian sizing), so consider one size up.'],
  ],
  3: [
    ['Good but not great', 'Decent quality, though I expected a bit more. Customer service on WhatsApp was quick to answer my questions.'],
  ],
  2: [
    ['Not for me', 'Nicely made, but it did not suit how I wanted to use it. The return in Dar was easy at least.'],
  ],
};

export const questions = [
  ['How long does delivery to Tanzania take?', 'Air cargo takes 10–14 days, express air 5–7 days and sea freight 30–45 days. We deliver to your door in Dar es Salaam, Arusha, Mwanza, Dodoma and other major towns.'],
  ['Do I have to pay customs when it arrives?', 'No. Import duties and clearing are handled by us. VAT (18%) is shown at checkout, so there are no surprises on delivery.'],
  ['Is this original quality?', 'Yes. We buy directly from verified factories in Guangzhou, Shenzhen and Yiwu and inspect every order before it ships to Tanzania.'],
  ['Can I return it if it doesn\'t suit me?', 'Yes. You have 14 days after delivery to return unused items. Drop-off is free at our Dar es Salaam collection point.'],
  ['Can I pay with M-Pesa?', 'Yes. We accept M-Pesa, Tigo Pesa, Airtel Money and HaloPesa, as well as Visa and Mastercard.'],
];

export const coupons = [
  { code: 'KARIBU10', description: '10% off your first order', type: 'percentage', value: 10, min: 0, limit: null, expires: 365 },
  { code: 'OKOA50', description: 'TSh 50,000 off orders over TSh 400,000', type: 'fixed', value: 50000, min: 400000, limit: 500, expires: 90 },
  { code: 'SIKUKUU20', description: '20% off sitewide (ended)', type: 'percentage', value: 20, min: 0, limit: 1000, expires: -10 },
];
